import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { userInfo } from "os";
import Providers from "./lib/Providers";
import Footer from "./components/pages/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await userInfo();
  return (
    <html
      lang="en"
      //  className="dark text-foreground bg-background"
    >
      <body>
        <Providers>
          <div className=" mx-auto container">
            <AntdRegistry>{children}</AntdRegistry>
          </div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
