import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../app/components/pages/shared/Footer";
import NavArea from "../app/components/pages/shared/Navbar";
import { userInfo } from "os";
import Providers from "./lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await userInfo();
  return (
    <html
      lang="en"
      //  className="dark text-foreground bg-background"
    >
      <body>
        <Providers>
          <div className=" mx-auto container">
            <NavArea />
            <div>{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
